revert

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-tf b/build-armbian/common-files/files/usr/sbin/armbian-tf
--- a/build-armbian/common-files/files/usr/sbin/armbian-tf
+++ b/build-armbian/common-files/files/usr/sbin/armbian-tf
@@ -8,19 +8,24 @@
 #=========================================================================
 
 # Set font color
-blue_font_prefix="\033[94m"
-purple_font_prefix="\033[95m"
-green_font_prefix="\033[92m"
-yellow_font_prefix="\033[93m"
-red_font_prefix="\033[91m"
+purple_font_prefix="\033[35m"
+green_font_prefix="\033[32m"
+red_font_prefix="\033[31m"
 font_color_suffix="\033[0m"
-INFO="[${blue_font_prefix}INFO${font_color_suffix}]"
 STEPS="[${purple_font_prefix}STEPS${font_color_suffix}]"
 SUCCESS="[${green_font_prefix}SUCCESS${font_color_suffix}]"
-OPT="[${yellow_font_prefix}OPT${font_color_suffix}]"
 ERROR="[${red_font_prefix}ERROR${font_color_suffix}]"
 
-echo -e "${INFO} Welcome to use TF/SD/USB partition management tool."
+echo -e "${STEPS} Try to create a shared partition..."
+
+echo -ne "${STEPS} This operation will clear the data in the remaining space, are you sure to continue? y/n [y]\b\b"
+read yn
+case $yn in
+n* | N*)
+    echo -e "${ERROR} You aborted the operation!"
+    exit 1
+    ;;
+esac
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
@@ -47,20 +52,16 @@ mmcblk?p[1-4])
     ;;
 esac
 
-# Create new partition
-create_new_part() {
-    echo -e "${STEPS} Start creating a new partition ... "
+# Get the starting position of the p3 partition
+START_P3=$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))
+if [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]]; then
+    echo -e "${ERROR} Unable to get starting position!"
+    exit 1
+fi
+TOTAL_SIZE=$(lsblk -l -b -o NAME,SIZE | awk "\$1 ~ /^${DISK_NAME}\$/ {print \$2}")
+END_P3=$((TOTAL_SIZE / 512 - 1))
 
-    # Get the starting position of the p3 partition
-    START_P3=$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))
-    if [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]]; then
-        echo -e "${ERROR} Unable to get starting position!"
-        exit 1
-    fi
-    TOTAL_SIZE=$(lsblk -l -b -o NAME,SIZE | awk "\$1 ~ /^${DISK_NAME}\$/ {print \$2}")
-    END_P3=$((TOTAL_SIZE / 512 - 1))
-
-    cat >/tmp/fdisk.script <<EOF
+cat >/tmp/fdisk.script <<EOF
 n
 p
 3
@@ -72,55 +73,24 @@ t
 83
 w
 EOF
-    sync
+sync
 
-    echo -e "${STEPS} Fdisk starting ... "
-    fdisk /dev/${DISK_NAME} </tmp/fdisk.script 2>/dev/null
-    if [ $? -ne 0 ]; then
-        echo -e "${ERROR} fdisk failed!"
-        exit 1
-    fi
-    sync
+echo -e "${STEPS} Fdisk starting ... "
+fdisk /dev/${DISK_NAME} </tmp/fdisk.script 2>/dev/null
+if [ $? -ne 0 ]; then
+    echo -e "${ERROR} fdisk failed!"
+    exit 1
+fi
+sync
 
-    echo -e "${STEPS} Create shared filesystem ... "
-    mkdir -p /mnt/${PT_PRE}3 && sync
-    mkfs.ext4 -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}3"
-    mount -t ext4 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
-    echo "/dev/${PT_PRE}3 /mnt/${PT_PRE}3 ext4 defaults 0 0" >>/etc/fstab
-    sync
+echo -e "${STEPS} Create shared filesystem ... "
+mkdir -p /mnt/${PT_PRE}3 && sync
+mkfs.ext4 -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}3"
+mount -t ext4 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
+echo "/dev/${PT_PRE}3 /mnt/${PT_PRE}3 ext4 defaults 0 0" >>/etc/fstab
+sync
 
-    echo -e "${INFO} The new partition information: \n$(df -hT /dev/${PT_PRE}3)"
-    echo -e "${SUCCESS} Create partition successfully, mount it in [ /mnt/${PT_PRE}3 ]"
-    rm -f /usr/sbin/armbian-tf 2>/dev/null && sync
-    sync
-    exit 0
-}
-
-# Expand the current partition
-expand_current_part() {
-    echo -e "${STEPS} Start to expand the current partition ... "
-
-    echo -e "${STEPS} Install growpart or xfsprogs expansion and formatting tool ... "
-    apt-get update
-    apt-get install cloud-guest-utils xfsprogs -y
-
-    echo -e "${STEPS} Expansion Partition ... "
-    growpart /dev/${DISK_NAME} 2
-
-    echo -e "${STEPS} Expansion file system ... "
-    resize2fs /dev/${ROOT_PTNAME}
-
-    echo -e "${INFO} Current partition information: \n$(df -hT /)"
-    echo -e "${SUCCESS} The current partition expansion is successful."
-    rm -f /usr/sbin/armbian-tf 2>/dev/null && sync
-    sync
-    exit 0
-}
-
-echo -ne "${OPT} Do you want to expand or create partitions? Expand=(e) Create=(c): "
-read ec
-case ${ec} in
-    e | E | expand) expand_current_part ;;
-    c | C | create) create_new_part ;;
-    *) exit 0 ;;
-esac
+echo -e "${SUCCESS} Create partition successfully, mount it in [ /mnt/${PT_PRE}3 ]"
+rm -f /usr/sbin/armbian-tf 2>/dev/null && sync
+sync
+exit 0
