Update use-releases-file-to-build.yml

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -94,27 +94,27 @@ jobs:
         run: |
           armbian_buildpath="build/output/images"
           [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
-          #down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
-          #down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
+          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
+          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
           #
           # down_filename: Armbian_Aml_bullseye_gnome_desktop_05.17.1924/Armbian_22.05.0-trunk_Odroidn2_bullseye_current_5.10.110.img.gz
-          #down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
-          #down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
-          #[ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
+          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
+          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
           cd "${armbian_buildpath}" && curl -# -LO https://github.com/kissyouhunter/amlogic-armbian/releases/download/Armbian/Armbian_22.08.0-trunk_${{ env.ARMBIAN_BOARD }}_${{ env.ARMBIAN_RELEASE }}_current_$BASE_KERNEL.img.gz
           cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
           #
           # down_tag: Armbian_Aml_bullseye_gnome_desktop
-          #down_tag="${down_filename%%/*}" && down_tag="${down_tag%_*}"
-          #echo "ARMBIAN_RELEASE=${down_tag}" >> $GITHUB_ENV
+          down_tag="${down_filename%%/*}" && down_tag="${down_tag%_*}"
+          echo "ARMBIAN_RELEASE=${down_tag}" >> $GITHUB_ENV
           #
           # down_board: bullseye
-          #down_board="$(echo ${down_tag} | cut -d"_" -f3)"
-          #echo "ARMBIAN_BOARD=${down_board}" >> $GITHUB_ENV
+          down_board="$(echo ${down_tag} | cut -d"_" -f3)"
+          echo "ARMBIAN_BOARD=${down_board}" >> $GITHUB_ENV
           #
           # down_edition: gnome_desktop
-          #down_edition="$(echo ${down_tag} | cut -d"_" -f4-)"
-          #echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
+          down_edition="$(echo ${down_tag} | cut -d"_" -f4-)"
+          echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
           #
           echo "::set-output name=status::success"
 
