update

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -1,16 +1,18 @@
-#========================================================================================================================
+#==========================================================================
 # Description: Build Armbian For Amlogic S9xxx STB
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
-# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
-#========================================================================================================================
+#==========================================================================
 
-name: Use Releases file to build
+name: Use Releases file to build armbian
 
 on:
   repository_dispatch:
   workflow_dispatch:
-  #schedule:
-    #- cron: '0 17 * * 0'
+    inputs:
+      sel_tags_keywords:
+        description: "Select tags keywords: bullseye / focal"
+        required: false
+        default: "bullseye"
 
 env:
   UPLOAD_FIRMWARE: false
@@ -23,56 +25,97 @@ jobs:
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
 
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
+    - name: telegrame_bot
       run: |
-        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq install $(curl -fsSL git.io/ubuntu-2004-server)
-        sudo -E apt-get -qq autoremove --purge
-        sudo -E apt-get -qq clean
-        sudo timedatectl set-timezone "$TZ"
-        echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
+        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
+          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：
+          您正在使用kissyouhunter仓库的Armbian for N1编译您自己的固件,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
+        fi      
 
-    - name: Make Armbian for amlogic s9xxx
-      id: make
-      if: (!cancelled())
+    - name: MachineType
       run: |
-        [ -d build/output/images ] || mkdir -p build/output/images
-        curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "Armbian_Aml_buster_.*/Armbian_.*-trunk_.*.img.gz" | head -n 1 > DOWNLOAD_ARMBIAN
-        [ -s DOWNLOAD_ARMBIAN ] && wget -q -P build/output/images https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMBIAN)
-        cd ./build/output/images && gzip -df *.img.gz && sync && cd ../../../
-        sudo chmod +x make
-        sudo ./make s905d 5.4.148
-        cd ./build/output/images && sudo gzip *.img && sync
-        echo "FILEPATH=$PWD" >> $GITHUB_ENV
-        echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-        echo "::set-output name=status::success"
+        cat /proc/cpuinfo
+        cat /proc/meminfo
+        cat /etc/issue
+        cat /proc/version   
 
-    - name: Upload artifact to Actions
-      uses: kittaakos/upload-artifact-as-is@master
-      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
-      with:
-        path: ${{ env.FILEPATH }}/
+      - name: Initialization environment
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
+          sudo -E apt-get -qq update
+          sudo -E apt-get -qq install $(curl -fsSL git.io/ubuntu-2004-server)
+          sudo -E apt-get -qq autoremove --purge
+          sudo -E apt-get -qq clean
+          sudo timedatectl set-timezone "$TZ"
+          echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
 
-    - name: Upload Armbian image to Release
-      id: release
-      uses: ncipollo/release-action@v1
-      if: steps.make.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
-      with:
-        tag: Armbian_Aml_buster_${{ env.FILE_DATE }}
-        artifacts: ${{ env.FILEPATH }}/*
-        allowUpdates: true
-        token: ${{ secrets.GITHUB_TOKEN }}
-        body: |
-          This is Armbian image for amlogic s9xxx STB
-          * Firmware information
-          Default username: root
-          Default password: 1234
-          Install to EMMC command: armbian-install
-          Update command: armbian-update
+      - name: Rebuild Armbian for amlogic s9xxx
+        id: rebuild
+        if: (!cancelled())
+        run: |
+          armbian_buildpath="build/output/images"
+          [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
+          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
+          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
+          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
+          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
+          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
+          cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
 
+          set_release="_"
+          out_releasename=$(ls -l *-trunk_* 2>/dev/null | awk '{print $9}' | head -n 1)
+          ARR_RELEASE=("bionic" "focal" "hirsute" "bullseye" "buster" "stretch")
+          i=1
+          for r in ${ARR_RELEASE[*]}; do
+              if [[ "${out_releasename}" == *${r}* ]]; then
+                  set_release="_${r}_"
+                  break
+              fi
+              let i++
+          done
+          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
+
+          cd ${GITHUB_WORKSPACE}
+          sudo chmod +x rebuild
+          sudo ./rebuild -d -b s905d 5.4.164_5.10.84_5.15.7
+          cd ./build/output/images && sudo gzip *.img && sync
+          echo "FILEPATH=$PWD" >> $GITHUB_ENV
+          echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
+          echo "::set-output name=status::success"
+
+      - name: Upload artifact to Actions
+        uses: kittaakos/upload-artifact-as-is@master
+        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+        with:
+          path: ${{ env.FILEPATH }}/
+
+      - name: Upload Armbian image to Release
+        id: release
+        uses: ncipollo/release-action@v1
+        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
+        with:
+          tag: Armbian_Aml${{ env.ARMBIAN_RELEASE }}${{ env.FILE_DATE }}
+          artifacts: ${{ env.FILEPATH }}/*
+          allowUpdates: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: |
+            This is Armbian image for amlogic s9xxx STB
+            * Firmware information
+            Default username: root
+            Default password: 1234
+            Install to EMMC command: armbian-install
+            Update command: armbian-update
+            
+    - name: telegram_bot
+      run: |
+        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
+          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：
+          您使用kissyouhunter仓库的Armbian for N1固件顺利编译完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
+        fi
+            
