rebuild

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -1,5 +1,5 @@
 #==========================================================================
-# Description: Build Armbian For Amlogic S9xxx STB
+# Description: Build Armbian For Amlogic s9xxx tv box
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
 #==========================================================================
 
@@ -12,13 +12,9 @@ on:
       sel_tags_keywords:
         description: "Select tags keywords: bullseye / focal"
         required: false
-        default: "bullseye"
+        default: "focal"
 
 env:
-  UPLOAD_FIRMWARE: true
-  UPLOAD_RELEASE: false
-  FILE_URL: https://github.com/kissyouhunter/amlogic-armbian/releases/download/Armbian/Armbian_22.02.0-trunk_Lepotato_bullseye_current_5.10.91.img.gz
-  FILE_NAME: Armbian_22.02.0-trunk_Lepotato_bullseye_current_5.10.91.img.gz
   TZ: Asia/Shanghai
 
 jobs:
@@ -29,20 +25,6 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-
-      - name: telegrame_bot
-        run: |
-          if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
-            curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：
-            您正在使用kissyouhunter仓库的Armbian for N1编译您自己的固件,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
-          fi      
-
-      - name: MachineType
-        run: |
-          cat /proc/cpuinfo
-          cat /proc/meminfo
-          cat /etc/issue
-          cat /proc/version   
 
       - name: Initialization environment
         env:
@@ -62,7 +44,12 @@ jobs:
         run: |
           armbian_buildpath="build/output/images"
           [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
-          wget -q -P "${armbian_buildpath}" "${FILE_URL}" && sync
+          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
+          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
+          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
+          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
+          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
           cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
 
           set_release="_"
@@ -80,39 +67,26 @@ jobs:
 
           cd ${GITHUB_WORKSPACE}
           sudo chmod +x rebuild
-          sudo ./rebuild -d -b s905d -k 5.4.170
-          cd ./build/output/images && sudo gzip *.img && rm -f ${FILE_NAME} && sync
+          sudo ./rebuild -d -b s922x_s905x3_s905d -k 5.15.13_5.10.90_5.4.170
+          sudo ./rebuild -d -b s922x-n2_s905x2_s905_s905d-ki_s912_s912-t95z_s905x_s905w -k 5.4.170
+          cd ./build/output/images && sudo gzip *.img && sync
           echo "FILEPATH=$PWD" >> $GITHUB_ENV
           echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
           echo "::set-output name=status::success"
 
-      - name: Upload artifact to Actions
-        uses: kittaakos/upload-artifact-as-is@master
-        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
-        with:
-          path: ${{ env.FILEPATH }}/
-
       - name: Upload Armbian image to Release
         id: release
         uses: ncipollo/release-action@v1
-        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
+        if: steps.rebuild.outputs.status == 'success' && !cancelled()
         with:
           tag: Armbian_Aml${{ env.ARMBIAN_RELEASE }}${{ env.FILE_DATE }}
           artifacts: ${{ env.FILEPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GITHUB_TOKEN }}
           body: |
-            This is Armbian image for amlogic s9xxx STB
+            This is Armbian image for Amlogic s9xxx tv box
             * Firmware information
             Default username: root
             Default password: 1234
             Install to EMMC command: armbian-install
             Update command: armbian-update
-            
-      - name: telegram_bot
-        run: |
-          if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
-            curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：
-            您使用kissyouhunter仓库的Armbian for N1固件顺利编译完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
-          fi
-            
