update

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -16,11 +16,11 @@ on:
       armbian_soc:
         description: "Set Amlogic SoC."
         required: false
-        default: "all"
+        default: "s905d"
       armbian_kernel:
         description: "Set kernel version."
         required: false
-        default: "5.15.25_5.10.100"
+        default: "5.4.197"
       armbian_size:
         description: "Set armbian rootfs size(Unit: MiB)."
         required: false
@@ -29,9 +29,15 @@ on:
         description: "Set armbian rootfs type: ext4 / btrfs"
         required: false
         default: "ext4"
+      set_board:
+        description: "BOARD: lepotato / odroidn2"
+        required: false
+        default: "odroidn2"  
 
 env:
   TZ: Asia/Shanghai
+  UPLOAD_FIRMWARE: true
+  BASE_KERNEL: 5.10.121
 
 jobs:
   build:
@@ -54,61 +60,85 @@ jobs:
           sudo timedatectl set-timezone "$TZ"
           echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
 
+      - name: telegrame_bot
+        run: |
+          ARR_RELEASE=("focal" "bullseye" "buster")
+          set_release="${{ github.event.inputs.sel_tags_keywords }}"
+          if  [[ -z "${set_release}" || -z "$(echo "${ARR_RELEASE[@]}" | grep -w "${set_release}")" ]]; then
+              set_release="focal"
+          fi
+          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
+
+          ARR_BOARD=("lepotato" "odroidn2")
+          set_board="${{ github.event.inputs.set_board }}"
+          if  [[ -z "${set_board}" || -z "$(echo "${ARR_BOARD[@]}" | grep -w "${set_board}")" ]]; then
+              set_board="lepotato"
+          fi
+          echo "ARMBIAN_BOARD=${set_board}" >> $GITHUB_ENV    
+
+          set_kernel="${{ github.event.inputs.armbian_kernel }}"
+          if [ "$set_kernel" = "none" ]; then
+            echo "no kernel was chosen"
+          else
+            echo "ARMBIAN_KERNEL=${set_kernel}" >> $GITHUB_ENV
+          fi
+
+          if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
+            curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：
+            您正在使用kissyouhunter仓库的Armbian_22.08.0-trunk_${{ env.ARMBIAN_BOARD }}_${{ env.ARMBIAN_RELEASE }}_current_${{ env.ARMBIAN_KERNEL }}编译您自己的固件,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
+          fi 
+
       - name: Download Armbian from Releases
         id: down
         if: (!cancelled())
         run: |
           armbian_buildpath="build/output/images"
           [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
-          down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
-          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
+          #down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
+          #down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
           #
           # down_filename: Armbian_Aml_bullseye_gnome_desktop_05.17.1924/Armbian_22.05.0-trunk_Odroidn2_bullseye_current_5.10.110.img.gz
-          down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
-          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
-          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
-          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
+          #down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
+          #down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
+          #[ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          cd "${armbian_buildpath}" && curl -# -LO https://github.com/kissyouhunter/amlogic-armbian/releases/download/Armbian/Armbian_22.08.0-trunk_${{ env.ARMBIAN_BOARD }}_${{ env.ARMBIAN_RELEASE }}_current_$BASE_KERNEL.img.gz
           cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
           #
           # down_tag: Armbian_Aml_bullseye_gnome_desktop
-          down_tag="${down_filename%%/*}" && down_tag="${down_tag%_*}"
-          echo "ARMBIAN_RELEASE=${down_tag}" >> $GITHUB_ENV
+          #down_tag="${down_filename%%/*}" && down_tag="${down_tag%_*}"
+          #echo "ARMBIAN_RELEASE=${down_tag}" >> $GITHUB_ENV
           #
           # down_board: bullseye
-          down_board="$(echo ${down_tag} | cut -d"_" -f3)"
-          echo "ARMBIAN_BOARD=${down_board}" >> $GITHUB_ENV
+          #down_board="$(echo ${down_tag} | cut -d"_" -f3)"
+          #echo "ARMBIAN_BOARD=${down_board}" >> $GITHUB_ENV
           #
           # down_edition: gnome_desktop
-          down_edition="$(echo ${down_tag} | cut -d"_" -f4-)"
-          echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
+          #down_edition="$(echo ${down_tag} | cut -d"_" -f4-)"
+          #echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
           #
           echo "::set-output name=status::success"
 
-      - name: Rebuild Armbian [ Board is ${{ env.ARMBIAN_BOARD }} / Edition is ${{ env.ARMBIAN_DESKTOP_OPT }} ]
-        uses: ophub/amlogic-s9xxx-armbian@main
-        if: steps.down.outputs.status == 'success' && !cancelled()
-        with:
-          build_target: armbian
-          armbian_path: build/output/images/*.img
-          armbian_soc: ${{ github.event.inputs.armbian_soc }}
-          armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
-          armbian_size: ${{ github.event.inputs.armbian_size }}
-          armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
-          armbian_sign: _${{ env.ARMBIAN_DESKTOP_OPT }}
+      - name: Rebuild Armbian for Amlogic s9xxx
+        id: rebuild
+        if: steps.compile.outputs.status == 'success' && !cancelled()
+        run: |
+          sudo chmod +x build-armbian/common-files/rootfs/usr/sbin/*
+          sudo chmod +x rebuild
+          sudo ./rebuild -d -b s905d -k ${{ env.ARMBIAN_KERNEL }}
+          cd build/output/images/ && sudo gzip *.img && sync
+          echo "FILEPATH=$PWD" >> $GITHUB_ENV
+          echo "FILE_DATE=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
+          echo "::set-output name=status::success"
 
-      - name: Upload Armbian image to Release
-        uses: ncipollo/release-action@main
-        if: env.PACKAGED_STATUS == 'success' && !cancelled()
+      - name: Upload Armbian image to Actions
+        uses: kittaakos/upload-artifact-as-is@master
+        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
         with:
-          tag: ${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
-          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
-          allowUpdates: true
-          token: ${{ secrets.GH_TOKEN }}
-          body: |
-            This is Armbian image for Amlogic s9xxx tv box
-            * Firmware information
-            Default username: root
-            Default password: 1234
-            Install command: armbian-install
-            Update command: armbian-update
-            Edition: ${{ env.ARMBIAN_DESKTOP_OPT }}
+          path: ${{ env.FILEPATH }}/
+
+      - name: telegram_bot
+        run: |
+          if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
+            curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：
+            您使用kissyouhunter仓库的Armbian_22.05.0-trunk_${{ env.ARMBIAN_BOARD }}_${{ env.ARMBIAN_RELEASE }}_current_${{ env.ARMBIAN_KERNEL }}固件顺利编译完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
+          fi          
